---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci)"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci)"
    ignore:
      - dependency-name: "com.puppycrawl.tools:checkstyle"
